RES_WIDTH = 800
RES_HEIGHT = 600
FPS = 30
SERVER = ("localhost",6804)
RECV_BUFF_SIZE = 512

SCREN_RES = (RES_WIDTH,RES_HEIGHT)
CARD_WIDTH = RES_HEIGHT/12
CARD_HEIGHT = RES_HEIGHT/8
CARD_SIZE = (CARD_WIDTH, CARD_HEIGHT)

